# Generated by Django 4.2.25 on 2025-10-29 04:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=200, verbose_name='Vendor Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('warranty_document', models.FileField(upload_to='warranties/', verbose_name='Warranty Document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warranty',
                'verbose_name_plural': 'Warranties',
                'ordering': ['-created_at'],
            },
        ),
    ]
